protocols:
  netconf:
    port: 8080
    rpc_timeout: 10 
  gnmi:
    port: 9339
    skip_verify: true 
modules:
  enricher:
    folder: "./"
    interval: 720
    workers: 2
    port: 10000
  portal:
    https: true
    server_crt: ""
    server_key: ""
    port: 8080

